const FOOD_HISTORIES_REQUIRED_FIELDS = [
  "food_id",
  "meal_category",
  "quantity",
  "date",
];

const FOOD_HISTORIES_ALLOWED_FIELDS = [...FOOD_HISTORIES_REQUIRED_FIELDS];

const FOOD_HISTORIES_FIELDS = [
  "id",
  "user_id",
  ...FOOD_HISTORIES_ALLOWED_FIELDS,
];

const FOOD_HISTORIES_SELECT_FIELDS_SQL = FOOD_HISTORIES_FIELDS.join(", ");

const FOOD_HISTORIES_TABLE_NAME = "food_histories";

module.exports = {
  FOOD_HISTORIES_REQUIRED_FIELDS,
  FOOD_HISTORIES_ALLOWED_FIELDS,
  FOOD_HISTORIES_FIELDS,
  FOOD_HISTORIES_SELECT_FIELDS_SQL,
  FOOD_HISTORIES_TABLE_NAME,
};
