const WEIGHT_HISTORIES_REQUIRED_FIELDS = ["date", "weight"];

const WEIGHT_HISTORIES_ALLOWED_FIELDS = [...WEIGHT_HISTORIES_REQUIRED_FIELDS];

const WEIGHT_HISTOIRES_FIELDS = [
  "id",
  "user_id",
  ...WEIGHT_HISTORIES_REQUIRED_FIELDS,
];

const WEIGHT_HISTORIES_SELECT_FIELDS_SQL = WEIGHT_HISTOIRES_FIELDS.join(", ");

const WEIGHT_HISTORIES_TABLE_NAME = "weight_histories";

module.exports = {
  WEIGHT_HISTORIES_REQUIRED_FIELDS,
  WEIGHT_HISTORIES_ALLOWED_FIELDS,
  WEIGHT_HISTOIRES_FIELDS,
  WEIGHT_HISTORIES_SELECT_FIELDS_SQL,
  WEIGHT_HISTORIES_TABLE_NAME,
};
